/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as App2Import } from './routes/app2'
import { Route as App1Import } from './routes/app1'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const App2Route = App2Import.update({
  id: '/app2',
  path: '/app2',
  getParentRoute: () => rootRoute,
} as any)

const App1Route = App1Import.update({
  id: '/app1',
  path: '/app1',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app1': {
      id: '/app1'
      path: '/app1'
      fullPath: '/app1'
      preLoaderRoute: typeof App1Import
      parentRoute: typeof rootRoute
    }
    '/app2': {
      id: '/app2'
      path: '/app2'
      fullPath: '/app2'
      preLoaderRoute: typeof App2Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app1': typeof App1Route
  '/app2': typeof App2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app1': typeof App1Route
  '/app2': typeof App2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app1': typeof App1Route
  '/app2': typeof App2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app1' | '/app2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app1' | '/app2'
  id: '__root__' | '/' | '/app1' | '/app2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  App1Route: typeof App1Route
  App2Route: typeof App2Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  App1Route: App1Route,
  App2Route: App2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app1",
        "/app2"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app1": {
      "filePath": "app1.tsx"
    },
    "/app2": {
      "filePath": "app2.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
